[workspace]
members = ["email-to-matrix", "encrypted-message", "encrypted-sender", "encryption-helper"]
resolver = "2"

[workspace.dependencies]
serde_json = "1.0"
serde = "1.0"
anyhow = "1.0.86"
futures-util = "0.3.30"
#matrix-sdk = "0.7.1"
matrix-sdk = { git = "https://github.com/matrix-org/matrix-rust-sdk"}
tokio = {version = "1.39.2",  features = ["macros", "rt-multi-thread"]}
url = "2.5.2"
rand = "0.8.5"
mailin = "0.6.4"
retry = "2.0.0"
aes-gcm = "0.10.3"
log = "0.4.22"
env_logger = "0.11.5"
mail-parser = "0.9.3"
crypto_box = { version = "0.9.1", features = ["chacha20"] }

