syntax = "proto3";
package matrix_room_server;

service matrix_room_server {
    rpc sync_public_keys(PublicKey) returns (PublicKey);
    rpc load_cipher(EncryptionData) returns (SessionState);
    rpc send(SendMessage) returns (Empty);
    rpc start(Empty) returns (Empty);
    rpc stop(Empty) returns (Empty);
}

message PublicKey {
    bytes public_key = 1;
}

message EncryptionData {
    bytes encryption_key_ciphertext = 1;
    bytes nonce = 2;
}

message SendMessage {
    string message = 1;
}

message Empty {}

enum SessionStateEnum {
    SessionExists = 0;
    SessionMissing = 1;
}

message SessionState {
    optional SessionStateEnum session_state = 1;
}



/*
    SessionExists,
    SessionMissing,
#[tarpc::service]
pub trait MatrixRoomServer {
    /// Receives the public key of the other side, processes it, and responds with the own one
    async fn sync_public_keys(alice_public_key: PublicKey) -> PublicKey;

    /// Loads the session for the client. sync_public_keys needs to be done beforehand. returns if it needs to restore or do interactive cross signing
    async fn load_cipher(
        encryption_key_ciphertext: Vec<u8>,
        nonce: Vec<u8>,
    ) -> Result<SessionState, String>;

    /// sends message to matrix room
    async fn send(message: String) -> Result<(), String>;

    /// simple start
    async fn start() -> Result<(), String>;

    /// stop the application
    async fn stop() -> Result<(), String>;
}
*/
