[package]
name = "encrypted-sender"
version = "0.1.0"
edition = "2021"

[dependencies]
crypto_box = { workspace = true }
clap = { workspace = true }
encrypted-startup = { path = "../encrypted-startup" }
tokio = { workspace = true }
tarpc = { workspace = true }
