[package]
name = "encrypted-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
tarpc = { workspace = true }
futures = { workspace = true }
crypto_box = { workspace = true }

